### ISSUE TITLE
项目在本地运行报错

### ISSUE THREAD

**Issue by chj-damon** [X-neuron/antdFront#10]
![image](https://user-images.githubusercontent.com/4902684/119471511-f12fc980-bd7b-11eb-9f53-6e270b67c61d.png)

**Comment by X-neuron** [comment]
我重新下了，win10 新环境下tyarn 拉包后 ，在node 16.1 和 node 14下 npm run dev/build 都可以哇 。办公室win7 也OK 
你的是苹果系统？

**Comment by chj-damon** [comment]
哦，我明白了，可能是我的node版本不对。我用高版本的node再试试。

**Comment by youngboo** [comment]
> 哦，我明白了，可能是我的node版本不对。我用高版本的node再试试。

你的好了吗，我mac系统试了也不行

**Comment by chj-damon** [comment]
我把node 切到v16.2试了一下，也是不行的。一直报这个错：
![image](https://user-images.githubusercontent.com/4902684/119614460-e4b97880-be30-11eb-9634-a1d6d3b2ddfe.png)
我是苹果系统

**Comment by chj-damon** [comment]
> 你的好了吗，我mac系统试了也不行

我的也不行。

**Comment by X-neuron** [comment]
> > 你的好了吗，我mac系统试了也不行
> 
> 我的也不行。
https://github.com/X-neuron/antdFront/issues/10#issuecomment-848511093  里面 有个 也是mac系统的。有问题，手工在chalk里删了个 platform ，看来这是个bug。得布个 苹果系统 测下 ，下次更新的时候 会修复这个问题。

预告：2.1版可能 权限系统会升级， 主要在实战过程中，前后端联调需要更好的属性级 casl 权限的表达...
typescript 预计在2.2版后再支持..

**Comment by chj-damon** [comment]
把recoil换成jotai吧，学习成本可以降一大截【手动滑稽】

**Comment by X-neuron** [comment]
> 把recoil换成jotai吧，学习成本可以降一大截【手动滑稽】
If your app heavily requires state serialization (storing state in storage, server, or URL), Recoil comes with good features.
https://docs.pmnd.rs/jotai/basics/comparison

**Comment by swiftwind0405** [comment]
mac下同样不行，求解决啊。。

**Comment by X-neuron** [comment]
> mac下同样不行，求解决啊。。

近期抽时间集中公关下~

**Comment by X-neuron** [comment]
> 哦，我明白了，可能是我的node版本不对。我用高版本的node再试试。
> mac下同样不行，求解决啊。。
> > > 你的好了吗，我mac系统试了也不行
> > 我的也不行。
> 估计是webpack的config有问题，回去再研究研究

webpack.config里 把 查找 ModuleScopePlugin 。注释掉 引入和使用这个插件的地方 截图所报的错误应该可以解决
 new ModuleScopePlugin(paths.appSrc, [
          paths.appPackageJson,
           reactRefreshOverlayEntry,
        ])
这个问题是 主要是引用 ModuleScopePlugin限制src 目录外的资源引入而导致的问题

**Comment by X-neuron** [comment]
> 哦，我明白了，可能是我的node版本不对。我用高版本的node再试试。
> mac下同样不行，求解决啊。。
> > > 你的好了吗，我mac系统试了也不行
> > 我的也不行。
> 估计是webpack的config有问题，回去再研究研究

webpack.config里 把 查找 ModuleScopePlugin 。注释掉 引入和使用这个插件的地方 截图所报的错误应该可以解决
 new ModuleScopePlugin(paths.appSrc, [
          paths.appPackageJson,
           reactRefreshOverlayEntry,
        ])
这个问题是 主要是引用 ModuleScopePlugin限制src 目录外的资源引入而导致的问题

**Comment by chj-damon** [comment]
那当时为什么需要这个ModuleScopePlugin插件？

**Comment by X-neuron** [comment]
> 那当时为什么需要这个ModuleScopePlugin插件？

问题解决了？
限制src 目录外的资源引入而导致的问题，有助于编译优化。照搬cra里的 代码过来的...觉得有用就保留了下来

**Comment by chj-damon** [comment]
能跑起来了，但是vue2的测试页面显示不出来，同时控制台有提示说locale加载失败

**Comment by X-neuron** [comment]
> 能跑起来了，但是vue2的测试页面显示不出来，同时控制台有提示说locale加载失败

example/vue2 的 那个 build下。然后 nginx 配个Ip + 端口 指到改dist路径下 。 config/route.js 改好哇~
下次 发个docker build文件吧...
