### ISSUE TITLE
想问一下，能不能出一份umi的版本

### ISSUE THREAD

**Issue by dongcer** [X-neuron/antdFront#13]

**Comment by X-neuron** [comment]
umi里有个 [umi-plugin-keep-alive](https://github.com/alitajs/umi-plugin-keep-alive) 插件 基于 [react-activation](https://github.com/CJY0208/react-activation)

是一套缓存方案。 也能用，但是解决不了一个tab 边上传文件，一个tab边填写表单的问题。

Umi 使用的dva数据流自带的路由，底层和react-router6 不一样。

muti-tab  也是可以做, 你可以参考下：
[react-antd-multi-tabs-admin](https://github.com/hsl947/react-antd-multi-tabs-admin) 它基于[react-redux](https://github.com/reduxjs/react-redux)拿到的路由。 

[ant-design-pro-plus](https://github.com/theprimone/ant-design-pro-plus)  这个用了[@umijs/route-utils](https://github.com/umijs/route-utils) 

用框架，在使用上 可能限制比较多。而且想 实验些新的想法 可能会比较费劲...  

Umi 框架要是和数据流解耦了，会考虑出umi 版..

用原生的技术，主要在技术自由...

基于这个模板，内部独立完成了一个后台管理系统，证明其有较强的可靠、可实践性.. 所以暂时没计划 出一个umi版

**Comment by dongcer** [comment]
关键是集成微前端+多标签TAB 我按照您的方法，但跳转我用的umi自带的，每次跳转整个tab都会触发一遍，而且qiankun微前端 会导致每个TabPane 渲染下都会有一个id root,导致切换很卡，所以这块想请大佬解惑一下

**Comment by X-neuron** [comment]
react-router6 发现路由改变触发一便render ,umi 自己的跳转也触一便render ..  有代码复现仓库么?

**Comment by 1195002442** [comment]
> 关键是集成微前端+多标签TAB 我按照您的方法，但跳转我用的umi自带的，每次跳转整个tab都会触发一遍，而且qiankun微前端 会导致每个TabPane 渲染下都会有一个id root,导致切换很卡，所以这块想请大佬解惑一下

请问你这问题后面解决了吗

**Comment by dongcer** [comment]
> 



> > 关键是集成微前端+多标签TAB 我按照您的方法，但跳转我用的umi自带的，每次跳转整个tab都会触发一遍，而且qiankun微前端 会导致每个TabPane 渲染下都会有一个id root,导致切换很卡，所以这块想请大佬解惑一下
> 
> 请问你这问题后面解决了吗

我没有用它的，用的umi-plugin-keep-alive

**Comment by 1195002442** [comment]
> 
请问有参考案例吗，你开启动态加载了吗，我微前端路由配置那块有点问题

**Comment by dongcer** [comment]
> > 
> 
> 请问有参考案例吗，你开启动态加载了吗，我微前端路由配置那块有点问题

手动加载的，因为配合tab切换路由那种自动加载的没办法整。例子都是我自己写的
