### ISSUE TITLE
项目本地启动报错

### ISSUE THREAD

**Issue by yuanhl1994** [X-neuron/antdFront#14]
项目本地报错，npm run dev ,注释对应模块，后续有其他模块报相同错误。mac,node 14.17.5
![image](https://user-images.githubusercontent.com/20420217/130408822-6fcef150-6eb6-467f-88dc-2389cd7244d2.png)
![image](https://user-images.githubusercontent.com/20420217/130409041-ce5d3b27-df01-46b2-a3e0-d6c68d8a38d7.png)

**Comment by yuanhl1994** [comment]
webpack版本问题解决了，不过启动还是有报错，而且assert-manifest也报404
![image](https://user-images.githubusercontent.com/20420217/130424831-1b1ac8fa-c966-4da0-b1a6-b8c41c1cd3a4.png)

**Comment by X-neuron** [comment]
devserver 和 webpack 版本升级 很多 破唤性更新 导致... 一会 修复~ 感谢~

**Comment by X-neuron** [comment]
npm build 下 ，nginx配下 测了是可以的... 基本是 devserver 到 4.0的更新配置问题了。

**Comment by X-neuron** [comment]
刚发了个小更新，没完全修复，有一个是：@pmmmwh/react-refresh-webpack-plugin 插件兼容devserver 4.0.0的问题。 已提交bug了，等那个插件修复吧。 
npm run build  是可以的....

**Comment by yuanhl1994** [comment]
> 刚发了个小更新，没完全修复，有一个是：@pmmmwh/react-refresh-webpack-plugin 插件兼容devserver 4.0.0的问题。 已提交bug了，等那个插件修复吧。
> npm run build 是可以的....

只有npm run build 然后放到服务器上运行么，直接npm run dev没发调试开发么

**Comment by X-neuron** [comment]
> 只有npm run build 然后放到服务器上运行么，直接npm run dev没发调试开发么

正在想办法解决.....

**Comment by X-neuron** [comment]
@pmmmwh/react-refresh-webpack-plugin 更新至 0.5 rc版 已修复 ..
