### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [X-neuron/antdFront#15]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by X-neuron** [comment]
@zidingz Thank you for your suggestion. I will seriously consider... Relevant documents will be added in the next version...

**Comment by X-neuron** [comment]
thanks so much ~

> Meanwhile, you can access this https://www.huntr.dev/bounties/bcd95e24-f967-4410-805a-d9f3b99642a0/ using GitHub OAuth and validate using `Mark as valid` and `confirm the fix`. Added a patch for this issue in huntr. Thank you.

Completed as required
