### ISSUE TITLE
启动后webpack报错

### ISSUE THREAD

**Issue by chj-damon** [X-neuron/antdFront#16]
最新的master分支代码，运行`yarn dev`后报错：
![image](https://user-images.githubusercontent.com/4902684/134308011-90069985-8863-4cf6-8ca0-9d54f6570b82.png)

**Comment by chj-damon** [comment]
node: v16.2.0
npm: 7.13.0
os: mac os 11.4

**Comment by X-neuron** [comment]
感谢您的反馈...

[https://github.com/X-neuron/antdFront/issues/10](url)  这里遇到类似的情况，当时 改完可能忘了发更新... 导致 这问题一直留着。

webpack.config里 把 查找 ModuleScopePlugin 。注释掉 引入和使用这个插件的地方 截图所报的错误应该可以解决
new ModuleScopePlugin(paths.appSrc, [
paths.appPackageJson,
reactRefreshOverlayEntry,
])
这个问题是 主要是引用 ModuleScopePlugin限制src 目录外的资源引入而导致的问题

**Comment by chj-damon** [comment]
已解决。
