### ISSUE TITLE
How to reduce the bundle size?

### ISSUE THREAD

**Issue by KrishnaPG** [X-neuron/antdFront#2]
Is there any way to reduce the bundle size? In the debug version it is producing 4MB+ and in release version almost 1MB+

How to use React, AntD etc. from the CDN (in the `<head>` tag of HTML) rather than bundling with webpack?

**Comment by X-neuron** [comment]
There were some solution : 
1、Extract common module in webpack4, using  SplitChunksPlugin and html-webpack-externals-plugin .
2、Extract common module in webpack5 for microfrontend scene，need the new module-federation trait。no example here。cause it's not published

here's the webpack4 using 'react' for example,

1、npm i html-webpack-externals-plugin -D

webpack.config.js :
```
new HtmlWebpackExternalsPlugin({
            externals: [
              {
                module: 'react',
                entry: 'https://cdn.bootcss.com/react/16.2.0/umd/react.production.min.js',  // your cdn address
                global: 'React',
              },
              {
                module: 'react-dom',
                entry: 'https://cdn.bootcss.com/react-dom/16.2.0/umd/react-dom.production.min.js',
                global: 'ReactDOM',
              }
            ]
        })
```
```

optimization: {
        splitChunks: {
            cacheGroups: {
                commons: {
                    test: /(react|react-dom)/,
                    name: 'vendors',
                    chunks: 'all'
                }
            }
        }
    },

```
2、The purpose here is to extract the react and react DOM, the public part, and package them into a file named vendors

Note that this is introduced in the chunks array in htmlwebpackplugin

```
htmlWebpackPlugins.push(
            new HtmlWebpackPlugin({
                template: path.join(__dirname, `src/index.html`),  // using your config
                filename: `index.html`, // using your config
                chunks: ['vendors', 'common','index'], 
                inject: true,
                minify: {
                    html5: true,
                    collapseWhitespace: true,
                    preserveLineBreaks: false,
                    minifyCSS: true,
                    minifyJS: true,
                    removeComments: false
                }
            })
        );

```

3、 Extract and package public files
```
optimization: {
        splitChunks: {
            minSize: 0,
            cacheGroups: {
                commons: {
                    name: 'commons',
                    chunks: 'all',
                    minChunks: 2
                }
            }
        }
    }

```
The minimum file size is 0. The files referenced at least twice will be packaged into a file named Commons. Here, as above, they need to be introduced into the chunks array in htmlwebpackplugin.
