### ISSUE TITLE
有计划升级成ts吗

### ISSUE THREAD

**Issue by qiujie8092916** [X-neuron/antdFront#21]

**Comment by X-neuron** [comment]
TS 版以前考虑过，但是前端都多只是curl  和 hook结合后，逻辑代码其实很少，页面往往比较独立不像后端有各种各样的关系，尤其上graphql后基本数据就是请求拿来的数据就用了....

不做底库 ，非巨石级应用，或企业协同开发 前端上ts 没有太大必要...
反而要为一大堆 接口类的定义头疼....
权限这块后期可能会更新 到支持A/B测试的 casl 。权限升级完后，如果casl 或 graphql 要求ts 那么可能会出ts 版的...

**Comment by qiujie8092916** [comment]
> TS 版以前考虑过，但是前端都多只是curl 和 hook结合后，逻辑代码其实很少，页面往往比较独立不像后端有各种各样的关系，尤其上graphql后基本数据就是请求拿来的数据就用了....
> 
> 不做底库 ，非巨石级应用，或企业协同开发 前端上ts 没有太大必要... 反而要为一大堆 接口类的定义头疼.... 权限这块后期可能会更新 到支持A/B测试的 casl 。权限升级完后，如果casl 或 graphql 要求ts 那么可能会出ts 版的...

我改了版ts的 [https://github.com/X-neuron/antdFront/pull/22](url)

**Comment by qiujie8092916** [comment]
首先感谢 @X-neuron 提供此仓库，对我这边有非常大的作用，不过我这边有些个性化的变动作为自用，ts是其中一环，所以我贡献了一版ts的

**Comment by X-neuron** [comment]
> 首先感谢 @X-neuron 提供此仓库，对我这边有非常大的作用，不过我这边有些个性化的变动作为自用，ts是其中一环，所以我贡献了一版ts的

十分感谢~  最近抽时间加紧测试。OK后 计划放typescript 分支~

**Comment by qiujie8092916** [comment]
> > 首先感谢 @X-neuron 提供此仓库，对我这边有非常大的作用，不过我这边有些个性化的变动作为自用，ts是其中一环，所以我贡献了一版ts的
> 
> 十分感谢~ 最近抽时间加紧测试。OK后 计划放typescript 分支~

改造过程中，发现两个问题：
1.在登录后，反复切换语言，会越来越慢，初步发现是BasicLayout里的深拷贝问题，因为ProLayout会修改传入值，选择降级pro-layout到~6.27.0替换深拷贝方案，可解决
2.切换语言并未更新到antd的组件上，表现为登录后，第一次切换到英文，右侧welcome页面内的内容成功切为英文，但再切回中文时，只有左侧菜单切换回了中文，右侧welcome页面内容并未切回中文，好像是某个recoil未触发（具体忘记了）

sorry，以上两点在提交的这版ts中好像并未更正，等后续有空再更正贡献 ^ ^

**Comment by X-neuron** [comment]
感谢反馈~
切换语言好像是有 个问题，第一切换很OK，之前的版本 没有这个问题，当时主要考虑为了用上recoil的selecter .. 会尽快修复~
antd支持动态换肤，但是prolayout 里 手工喂的 menu 配置好像换不了... 是Prolayout的问题。近期会反馈给他们..等待修复。。

**Comment by X-neuron** [comment]
> 改造过程中，发现两个问题： 1.在登录后，反复切换语言，会越来越慢，初步发现是BasicLayout里的深拷贝问题，因为ProLayout会修改传入值，选择降级pro-layout到~6.27.0替换深拷贝方案，可解决 2.切换语言并未更新到antd的组件上，表现为登录后，第一次切换到英文，右侧welcome页面内的内容成功切为英文，但再切回中文时，只有左侧菜单切换回了中文，右侧welcome页面内容并未切回中文，好像是某个recoil未触发（具体忘记了）

最近刚抽出时间  准备更新，刚上了 18。 目测 升级后的batchupdate 自动修复这个语言切换的问题，上18后挺顺滑..

**Comment by X-neuron** [comment]
非常感谢，主分支已切换至typescript 版~
