### ISSUE TITLE
微应用内部跳转，刷新页面报错

### ISSUE THREAD

**Issue by beibeibear** [X-neuron/antdFront#4]
![image](https://user-images.githubusercontent.com/12797471/101770683-c6cab680-3b23-11eb-85eb-e3c0b751cdde.png)

**Comment by beibeibear** [comment]
例如 http://localhost:8080/vue/about

**Comment by X-neuron** [comment]
感谢您的反馈~

登录状态 没做持久化，刷新页面，理论上 应该是跳转到登陆页面。
刚项目里新附上了一段nginx.conf的配置。环境重建了下，刷新的结果，符合预期..

2.0正在重写，主要卡在tab的嵌套路由上。如果使用react-keep之类的，也会其他的一些小问题。
在路由这块，有可能会 采用传统路由，上到react-router6 因为 reach router和 react router合并了。
主要因为非路由的方式，实现页面和按钮级权限很方便。但在嵌套路由的使用比较困难。

**Comment by beibeibear** [comment]
我把刷新重定向到登陆页面那块逻辑暂时先注释掉，刷新只是刷新当前页面，然后刷新微应用的子页面，例如/about页面，页面会报错。。。

**Comment by beibeibear** [comment]
loadmicroapp只能加载微应用的根路径。。

**Comment by X-neuron** [comment]
仔细看了几遍，这个vue2的样例，好像动了根路由.... 记忆中，好像qiankun有人pr样例问题，然后他们改了vue2的样例，我这可没更新，有可能说的是这个问题。
http://localhost:8080/micro/vue2 能导到页面，但是那个about 对应的是 http://localhost:8080/vue/about 所以 用http://localhost:8080/micro/vue2/about 也导不过去..

点点vue的 几个 按钮： 他切换到http://localhost:8080/vue  http://localhost:8080/vue/about了。
所以在 basicLayout 中的 openRoute的时候 pickup不到对应的组件了...

**Comment by X-neuron** [comment]
v2 原生组件 支持路由的多标签 已经可以预览了，全网目前独一份.. 欢迎测试

**Comment by whenTheMorningDark** [comment]
请问下 微服务那个模块有提交到最新的代码吗？因为我现在跳转还是会出现报错。

**Comment by X-neuron** [comment]
> 请问下 微服务那个模块有提交到最新的代码吗？因为我现在跳转还是会出现报错。

是V2么，v2 微前端 路由这块 还需要调整下...

**Comment by whenTheMorningDark** [comment]
> > 请问下 微服务那个模块有提交到最新的代码吗？因为我现在跳转还是会出现报错。
> 
> 是V2么，v2 微前端 路由这块 还需要调整下...

是v2,期待更新

**Comment by X-neuron** [comment]
v2 微端 子应用路由已经Ok了。
```
useMount(() => {
    microApp.current = loadMicroApp({
      name: `app${containerID.current}`,
      entry,
      // container: `#${id}`,
      props:{
        basePath:fullPath  //注入了微端的basepath
      },
      container: `#${containerID.current}`,
    }, {
      sandbox: { strictStyleIsolation: true },
      singular: false
    });

  });
```

在子应用中 以vue 为例：
```
function render(props = {}) {
  const { container,basePath } = props;
  console.log(props);
  router = new VueRouter({
    base: window.__POWERED_BY_QIANKUN__ ? basePath : '/',
    mode: 'history',
    routes,
  });
```
即可，详情参见 example

**Comment by X-neuron** [comment]
> 是v2,期待更新
 v2的  微前端 OK了~

**Comment by X-neuron** [comment]
v2正式发布，问题已修复。欢迎下载新版
