### ISSUE TITLE
大哥，你这个迁移完成了吗？

### ISSUE THREAD

**Issue by mylovetop** [X-neuron/antdFront#5]
大哥，你这个迁移完成了吗？

**Comment by X-neuron** [comment]
国际化、数据流和布局都迁完了。
主要在权衡 tab和回到router 之间，还没最后定..
上了router的话，要实现tab 比较困难，有react keep 也有会其他小问题.. 不用router 在嵌套路由的使用上，比较困难..

**Comment by X-neuron** [comment]
v2 可以预览了。全网独一份，react-router6 带路由的 多无缓存 原生组件 的多标签

**Comment by X-neuron** [comment]
v2 正式发布，问题已修复
