### ISSUE TITLE
哥哥,你这个做到了微前端主体的多标签嘛,还能保留状态.

### ISSUE THREAD

**Issue by windyzoe** [X-neuron/antdFront#6]
各个微应用在不同的标签页里切来切去,还保留状态?求原理,等我跑一遍再聊哈

**Comment by windyzoe** [comment]
我知道了，每个tab都重新走了一遍reactdom render

**Comment by windyzoe** [comment]
哭了，没跑起来
Module not found: You attempted to import /antdFront/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
src/app.jsx

**Comment by X-neuron** [comment]
> 我知道了，每个tab都重新走了一遍reactdom render

状态保留 主要是 没有使用路由...  只用了抽取了路由算法... 用的UI原生的tab 组件
理论上 不会每个tab 都重渲染...

**Comment by X-neuron** [comment]
> 哭了，没跑起来
> Module not found: You attempted to import /antdFront/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
> src/app.jsx

开热载了？ react refresh 在webpack5 下还没完全稳定....

**Comment by windyzoe** [comment]
> > 哭了，没跑起来
> > Module not found: You attempted to import /antdFront/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
> > src/app.jsx
> 
> 开热载了？ react refresh 在webpack5 下还没完全稳定....

直接拉项目，npm i，npm run dev，没跑起来

**Comment by X-neuron** [comment]
> 直接拉项目，npm i，npm run dev，没跑起来

可能是 node 版本的事...
推荐14.15.1 tls版
有几个库 比如 nano依赖 node 13.5以上...

刚重下 试了下
 cnpm i 
 npm i
 yarn 
 tyarn 都可以...

**Comment by windyzoe** [comment]
> > 直接拉项目，npm i，npm run dev，没跑起来
> 
> 可能是 node 版本的事...
> 推荐14.15.1 tls版
> 有几个库 比如 nano依赖 node 13.5以上...
> 
> 刚重下 试了下
> cnpm i
> npm i
> yarn
> tyarn 都可以...
这样啊，尼玛我公司的打包机还得生个版本才行

**Comment by windyzoe** [comment]
还是不行，mac ，node 14.15 ，现在爆process is not defined

**Comment by windyzoe** [comment]
总算跑起来了，我手动把chalk里的一个process.platform给删了才跑起来的，为啥还依赖这个

**Comment by X-neuron** [comment]
> 总算跑起来了，我手动把chalk里的一个process.platform给删了才跑起来的，为啥还依赖这个

你是mac版的啊.... 看来以后得装个虚拟机 整个mac环境测测。
应该是里面的跨平台配置这块 一些变量调用的函数bug...

**Comment by X-neuron** [comment]
2.0  分支 已经可以 预览了... 还有权限和 prolayout 没完全调通。其他OK了

**Comment by X-neuron** [comment]
v2 正式发布，问题已修复
