### ISSUE TITLE
npm run dev 运行不起来

### ISSUE THREAD

**Issue by mylovetop** [X-neuron/antdFront#7]
× Webpack
  Compiled with some errors in 46.54s

(node:24084) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use o
ne of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
npm run dev 运行不起来  一直停留在此状态

**Comment by X-neuron** [comment]
新年好哇~。你的Node 版本是？ 系统是苹果的？

(node:14580) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at E:\project\antdFront-git\node_modules\_postcss-safe-
√ Webpack
  Compiled successfully in 26.15s

(node:14580) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at E:\project\antdFront-git\node_modules\_postcss-safe-parser@5.0.2@postcss-safe-parser\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:14580) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from E:\project\antdFront-git\public
i ｢wds｣: 404s will fallback to /
(node:14580) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at E:\project\antdFront-git\node_modules\_css-loader@5.0.2@css-loader\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".

√ Webpack
  Compiled successfully in 18.39s

**Comment by mylovetop** [comment]
大哥 新年好！
windows7 
node v12.18.3
npm 6.14.6

**Comment by mylovetop** [comment]
npm WARN @reach/router@1.3.4 requires a peer of react-dom@15.x || 16.x || 16.4.0-alpha.0911da3 but none is installed. You must install peer dependencies yourself.
npm WARN @umijs/hooks@1.9.3 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
npm WARN @umijs/use-request@1.4.3 requires a peer of react@^16.8.6 but none is installed. You must install peer dependencies yourself.
npm WARN antd@4.12.2 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-styled-components@1.12.0 requires a peer of styled-components@>= 2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@6.0.0 requires a peer of eslint-plugin-flowtype@^5.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN mini-store@3.0.6 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN optimize-css-assets-webpack-plugin@5.0.4 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-align@4.0.9 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-cascader@1.4.2 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-checkbox@2.3.2 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-collapse@3.1.0 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-dialog@8.5.1 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-drawer@4.2.2 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-field-form@1.18.1 requires a peer of react@>= 16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-image@5.2.1 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-input-number@6.2.0 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-mentions@1.5.3 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-menu@8.10.5 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-motion@2.4.1 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-notification@4.5.4 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-overflow@1.0.2 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-pagination@3.1.3 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-picker@2.5.2 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-progress@3.1.3 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-rate@2.9.1 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-resize-observer@1.0.0 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-slider@9.7.1 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-steps@4.1.3 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-switch@3.2.2 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-table@7.13.1 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-tabs@11.7.3 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-textarea@0.3.4 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-tooltip@5.0.2 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-trigger@5.2.1 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-upload@3.3.4 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-util@5.8.0 requires a peer of react@>=16.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-dom@17.0.1 requires a peer of react@17.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-perf-devtool@3.1.8 requires a peer of react-dom@^16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-reconciler@0.25.1 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.20.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7
.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN webpackbar@4.0.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN antdfront@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

removed 6 packages and audited 2403 packages in 17.451s

182 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

是npm 拉包 没拉完？

**Comment by X-neuron** [comment]
npm 经常有拉不完的情况，你的情况应该是node 版本的问题，依赖库的好像有要求 node >13 .推荐你用nvm 管理下你的node 版本。
npm i cnpm yarn tyarn -g
删除node_modules 然后 tyarn 试试...

2.0快调完了，react router6  recoil数据流，lingui 国际化   。最近一个月会发,..

**Comment by mylovetop** [comment]
哥  我用yarn 把包拉完了，现在编译出现这样
√ Webpack
  Compiled successfully in 27.73s

(node:14528) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use o
ne of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
停在此处了

**Comment by mylovetop** [comment]
大哥， 找到问题了，现在可以正常跑起来了，端口号8080被其他程序占了， 这个端口号 哪里修改。
