### ISSUE TITLE
大哥，可以用vite 来构建项目吗

### ISSUE THREAD

**Issue by mylovetop** [X-neuron/antdFront#8]
大哥，可以用vite 来构建项目吗，webpack 看起来太繁琐，vite 大概了解下貌似很简洁

**Comment by X-neuron** [comment]
昨天试了下vite ，vite 对 jsx 支持不是很好。 
下的vite的官方react 模板， 对react 17 支持不好。

**Comment by mylovetop** [comment]
ok
